<div id="fb-root"></div>
<script>(function(d, s, id) {
    var js, fjs = d.getElementsByTagName(s)[0];
    if (d.getElementById(id)) return;
    js = d.createElement(s); js.id = id;
    js.src = "//connect.facebook.net/en_GB/all.js#xfbml=1";
    fjs.parentNode.insertBefore(js, fjs);
}(document, 'script', 'facebook-jssdk'));</script>

<div class="page-title">
    <h1><?php echo $this->__('Your order has been received') ?></h1>
</div>
<?php echo $this->getMessagesBlock()->getGroupedHtml() ?>
<p><strong><?php echo $this->__('Thank you for your purchase!') ?></strong></p>

<?php if ($this->getOrderId()):?>
<?php if ($this->getCanViewOrder()) :?>
    <p><?php echo $this->__('Your order # is: %s.', sprintf('<a href="%s">%s</a>', $this->escapeHtml($this->getViewOrderUrl()), $this->escapeHtml($this->getOrderId()))) ?></p>
<?php  else :?>
    <p><?php echo $this->__('Your order # is: %s.', $this->escapeHtml($this->getOrderId())) ?>.</p>
<?php endif;?>
    <p><?php echo $this->__('You will receive an order confirmation email with details of your order and a link to track its progress.') ?></p>
<?php if ($this->getViewOrder() && $this->getCanPrintOrder()) :?>
    <p>
        <?php echo $this->__('Click <a href="%s" onclick="this.target=\'_blank\'">here to print</a> a copy of your order confirmation.', $this->getPrintUrl()) ?>
        <?php echo $this->getChildHtml() ?>
    </p>
<?php endif;?>
<?php endif;?>

<?php if ($this->getAgreementRefId()): ?>
    <p><?php echo $this->__('Your billing agreement # is: %s.', sprintf('<a href="%s">%s</a>', $this->escapeHtml($this->getAgreementUrl()), $this->escapeHtml($this->getAgreementRefId())))?></p>
<?php endif;?>

<?php if ($profiles = $this->getRecurringProfiles()):?>
<p><?php echo $this->__('Your recurring payment profiles:'); ?></p>
<ul>
<?php foreach($profiles as $profile):?>
<?php $profileIdHtml = ($this->getCanViewProfiles() ? sprintf('<a href="%s">%s</a>', $this->escapeHtml($this->getProfileUrl($profile)), $this->escapeHtml($this->getObjectData($profile, 'reference_id'))) : $this->escapeHtml($this->getObjectData($profile, 'reference_id')));?>
    <li><?php echo $this->__('Payment profile # %s: "%s".', $profileIdHtml, $this->escapeHtml($this->getObjectData($profile, 'schedule_description')))?></li>
<?php endforeach;?>
</ul>
<?php endif;?>

<?php 
if (Mage::getStoreConfig('ordershare/design/enabled')) {?>


<?php if ($this->getOrderId()):?>
    <div class="ordershare">
        <h2><?php echo $this->__('Why not share your purchase to twitter, facebook or Linkedin?') ?></h2>
        <?php $order = $this->getOrder(); ?>
        
        <?php $_columnCount = $this->getColumnCount(); ?>
        <?php $_products = $order->getAllVisibleItems() ?>
        <?php $_collectionSize = count($_products) ?>
        <ul class="products-grid">
        <?php $i=0; foreach ( $_products as $item ) : ?>
            <?php $_product = $this->getOrderedProduct($item)?>
            <?php $_helper = $this->helper('catalog/output'); ?>
            <?php $_twitter_text = $this->__("I just bought a %s from %s", $_product->getName(), $this->getStoreName()); ?>
            <?php $_linkedin_text = $this->__("I just bought a %s from %s", $_product->getName(), $this->getStoreName()); ?>
            <?php $_twitter_user = $this->getTwitterUser(); ?>
            
                
                                
            <li class="item">
                <?php if ($_product->getImage()) :?>
                <div class="product-image">
                    <?php $_img = '<img src="'.$this->helper('catalog/image')->init($_product, 'small_image')->resize(135).'" alt="'.$this->htmlEscape($this->getImageLabel()).'" title="'.$this->htmlEscape($this->getImageLabel()).'" />'; 
                        echo $_helper->productAttribute($_product, $_img, 'image'); ?>
                </div>
                <?php endif; ?>
                <h2 class="product-name"><?php echo $_product->getName() ?></h2>
                    <script src="http://platform.twitter.com/widgets.js" type="text/javascript"></script>
                    <?php $_twitter_url = $this->getTwitterUrl($_twitter_text, $_product) ?>
                    <?php $_facebook_url = $this->getFacebookUrl($_product) ?>
                    <?php $_linkedin_url = $this->getLinkedinUrl($_linkedin_text, $_product) ?>
                    <?php  $_google_url = $this->getGoogleUrl($_product) ?>
                    <?php  $_pin_url = $this->getPinUrl($_product) ?>
                    <?php $_stumble_url = $this->getStumbleUrl($_product) ?>
                     
                    <ul>
                        <?php if (Mage::getStoreConfig('ordershare/design/twitter')) {?>
                        <li class="twitter"><a target="_blank" title="twitter" href="<?php echo $_twitter_url; ?>">t</a></li>
                         <?php } ?>
                         <?php if (Mage::getStoreConfig('ordershare/design/facebook')) {?>
                        <li class="facebook"><a target="_blank" title="facebook" href="<?php echo $_facebook_url; ?>">f</a></li>
                         <?php } ?>
                         <?php if (Mage::getStoreConfig('ordershare/design/linkedin')) {?> 
                        <li class="linkedin-sharing"><a target="_blank" title="Linkedin" href="<?php echo $_linkedin_url; ?>">in</a></li>
                         <?php } ?>
                         <?php if (Mage::getStoreConfig('ordershare/design/googleplus')) {?> 
                        <li class="google"><a target="_blank" title="googleplus" href="<?php echo $_google_url; ?>">g+</a></li>
                          <?php } ?> 
                          <?php if (Mage::getStoreConfig('ordershare/design/pinterest')) {?>
                        <li class="pintrest"><a target="_blank" title="pintrest" href="<?php echo $_pin_url; ?>">p</a></li>
                           <?php } ?> 
                         <?php if (Mage::getStoreConfig('ordershare/design/stumbleupon')) {?>
                        <li class="stumble"><a target="_blank" title="stumble upon" href="<?php echo $_stumble_url; ?>">Su</a></li> 
                        <?php } ?>
                        
                    </ul>
            </li>
              
        
        <?php endforeach; ?>
         </ul>
    </div>
    <?php endif; ?> 
<div class="buttons-set">
    <button type="button" class="button" title="<?php echo $this->__('Continue Shopping') ?>" onclick="window.location='<?php echo $this->getUrl() ?>'"><span><span><?php echo $this->__('Continue Shopping') ?></span></span></button>
</div>
<?php }?>
