<div id="fb-root"></div>
<script>(function(d, s, id) {
    var js, fjs = d.getElementsByTagName(s)[0];
    if (d.getElementById(id)) return;
    js = d.createElement(s); js.id = id;
    js.src = "//connect.facebook.net/en_GB/all.js#xfbml=1&appId=446177488757452";
    fjs.parentNode.insertBefore(js, fjs);
}(document, 'script', 'facebook-jssdk'));</script>

<div class="page-title">
    <h1><?php echo $this->__('Order Success') ?></h1>
</div>
<p><strong><?php echo $this->__('Thank you for your purchase!') ?></strong></p>
<p><?php echo $this->__('We are processing your order and you will soon receive an email with details of the order. Once the order has shipped you will receive another email with a link to track its progress.') ?></p>
<?php if($_orderIds = $this->getOrderIds()): ?>
<p>
    <?php $flag = false ?>
    <?php echo $this->__('Your order number is ') ?>
    <?php foreach ($_orderIds as $orderId=>$incrementId): ?>
        <?php if ($flag): ?>
            <?php echo ', ' ?>
        <?php endif; ?>
        <?php $flag = true ?>
        <a href="<?php echo $this->getViewOrderUrl($orderId) ?>"><?php echo $incrementId ?></a>
    <?php endforeach; ?>
</p>
<?php endif; ?>
<?php echo $this->getChildHtml() ?>


<?php 
if (Mage::getStoreConfig('ordershare/design/enabled')) {?>

<?php if (isset($_orderIds)):?>
   <div class="ordershare">
        <h2><?php echo $this->__('Why not share your purchase to twitter or facebook?') ?></h2>
        <?php foreach ($_orderIds as $orderId=>$incrementId): ?>
            <?php $order = Mage::getModel('sales/order')->loadByIncrementId($incrementId); ?>

            <?php $_columnCount = $this->getColumnCount(); ?>
            <?php $_products = $order->getAllVisibleItems() ?>
            <?php $_collectionSize = count($_products) ?>

            <?php $i = 0; foreach ( $order->getAllItems() as $item ) : ?>
                <?php $_product = Mage::getModel('catalog/product')->load($item->getProductId()); ?>
                <?php
                    if (!$_product->isVisibleInSiteVisibility()) {
                        continue;
                  }
                ?>

                <?php if ($i++%$_columnCount==0): ?>
                     <ul class="products-grid">
                 <?php endif ?>

           <?php $_helper = $this->helper('catalog/output'); ?>
                <?php $_twitter_text = $this->__("I just bought a %s from %s", $_product->getName(), $this->getStoreName()); ?>
                 <?php $_pin_text = $this->__("I just bought a %s from %s", $_product->getName(), $this->getStoreName()); ?>
                <?php $_twitter_user = $this->getTwitterUser(); ?>
                                    

            <li class="item<?php if(($i-1)%$_columnCount==0): ?> first<?php elseif($i%$_columnCount==0): ?> last<?php endif; ?>">
                <?php if ($_product->getImage()) :?>
                    <div class="product-image">
                        <?php $_img = '<img src="'.$this->helper('catalog/image')->init($_product, 'small_image')->resize(135).'" alt="'.$this->htmlEscape($this->getImageLabel()).'" title="'.$this->htmlEscape($this->getImageLabel()).'" />';
                        echo $_helper->productAttribute($_product, $_img, 'image'); ?>
                    </div>
                <?php endif; ?>

                <h2 class="product-name"><?php echo $_product->getName() ?></h2>
                    <script src="http://platform.twitter.com/widgets.js" type="text/javascript"></script>
                    <?php $_twitter_url = $this->getTwitterUrl($_twitter_text, $_product) ?>
                    <?php $_facebook_url = $this->getFacebookUrl($_product) ?>
                    <?php $_linkedin_url = $this->getLinkedinUrl($_linkedin_text, $_product) ?>
                    <?php  $_google_url = $this->getGoogleUrl($_product) ?>
                    <?php $_stumble_url = $this->getStumbleUrl($_product) ?>
                     
                    <ul>
                        <?php if (Mage::getStoreConfig('ordershare/design/twitter')) {?>
                        <li class="twitter"><a target="_blank" href="<?php echo $_twitter_url; ?>">t</a></li>
                         <?php } ?>
                         <?php if (Mage::getStoreConfig('ordershare/design/facebook')) {?>
                        <li class="facebook"><a target="_blank" href="<?php echo $_facebook_url; ?>">f</a></li>
                         <?php } ?>
                         <?php if (Mage::getStoreConfig('ordershare/design/linkedin')) {?> 
                        <li class="linkedin-sharing"><a target="_blank" href="<?php echo $_linkedin_url; ?>">in</a></li>
                         <?php } ?>
                         <?php if (Mage::getStoreConfig('ordershare/design/googleplus')) {?> 
                        <li class="google"><a  target="_blank" href="<?php echo $_google_url; ?>">g+</a></li>
                          <?php } ?> 
                          <?php if (Mage::getStoreConfig('ordershare/design/pinterest')) {?>
                        <li class="pintrest"><a  target="_blank" href="<?php echo $_pin_url; ?>"> p</a></li>
                           <?php } ?> 
                         <?php if (Mage::getStoreConfig('ordershare/design/stumbleupon')) {?>
                        <li class="stumble"><a  target="_blank" href="<?php echo $_stumble_url; ?>">Stumbleupon</a></li> 
                        <?php } ?>
                        
                    </ul>
            
            
            </li>
            <?php if ($i%$_columnCount==0 || $i==$_collectionSize): ?>
                </ul>
            <?php endif ?>


        <?php endforeach; ?>
        <?php endforeach; ?>
    </div>
<?php endif; ?> 


<div class="buttons-set">
    <button type="button" title="<?php echo $this->__('Continue Shopping') ?>" class="button" onclick="setLocation('<?php echo $this->getContinueUrl() ?>')"><span><span><?php echo $this->__('Continue Shopping') ?></span></span></button>
</div>
<?php }?>
